export const COUNT_PREFERENCES = "COUNT_PREFERENCES";
export const REMOVE_COUNT_PREFERENCES = "REMOVE_COUNT_PREFERENCES";

export const ADD_PREFERENCES_LOADING = "ADD_PREFERENCES_LOADING";
export const ADD_PREFERENCES_SUCCESS = "ADD_PREFERENCES_SUCCESS";
export const ADD_PREFERENCES_FAIL = "ADD_PREFERENCES_FAIL";