export const GET_REELS_LOADING = "GET_REELS_LOADING";
export const GET_REELS_SUCCESS = "GET_REELS_SUCCESS";
export const GET_REELS_ERROR = "GET_REELS_ERROR";

export const ADD_REELS_REQUEST = "ADD_REELS_REQUEST";
export const ADD_REELS_SUCCESS = "ADD_REELS_SUCCESS";
export const ADD_REELS_FAIL = "ADD_REELS_FAIL";
export const ADD_REELS_REMOVE = "ADD_REELS_REMOVE";