export const ADD_STORY_LOADING = "ADD_STORY_LOADING";
export const ADD_STORY_SUCCESS = "ADD_STORY_SUCCESS";
export const ADD_STORY_FAIL = "ADD_STORY_FAIL";
export const ADD_STORY_REMOVE = "ADD_STORY_REMOVE";

export const GET_ALL_STORIES_LOADING = "GET_ALL_STORIES_LOADING";
export const GET_ALL_STORIES_SUCCESS = "GET_ALL_STORIES_SUCCESS";
export const GET_ALL_STORIES_FAIL = "GET_ALL_STORIES_FAIL";