export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT"

export const GET_TOP_USERS_REQUEST = "GET_TOP_USERS_REQUEST";
export const GET_TOP_USERS_SUCCESS = "GET_TOP_USERS_SUCCESS";
export const GET_TOP_USERS_FAIL = "GET_TOP_USERS_FAIL";

export const GET_SEARCH_RESULTS_REQUEST = "GET_SEARCH_RESULTS_REQUEST";
export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAIL = "GET_SEARCH_RESULTS_FAIL";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const GET_USER_SUGGESTIONS_REQUEST = "GET_USER_SUGGESTIONS_REQUEST";
export const GET_USER_SUGGESTIONS_SUCCESS = "GET_USER_SUGGESTIONS_SUCCESS";
export const GET_USER_SUGGESTIONS_FAIL = "GET_USER_SUGGESTIONS_FAIL";

export const GET_USER_MUTUAL_SUGGESTIONS_REQUEST = "GET_USER_MUTUAL_SUGGESTIONS_REQUEST";
export const GET_USER_MUTUAL_SUGGESTIONS_SUCCESS = "GET_USER_MUTUAL_SUGGESTIONS_SUCCESS";
export const GET_USER_MUTUAL_SUGGESTIONS_FAIL = "GET_USER_MUTUAL_SUGGESTIONS_FAIL";